   name: Build and Deploy
   on:
     push:
       branches: [master]
   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       env:
         NETLIFY_CMS_BASE_URL: ${{ secrets.NETLIFY_CMS_BASE_URL }}
       steps:
         - uses: actions/checkout@v2
         
         - name: Replace base_url placeholder
           run: |
             sed -i "s|NETLIFY_CMS_BASE_URL_PLACEHOLDER|${{ secrets.NETLIFY_CMS_BASE_URL }}|g" admin/config.yml
         
         - name: Debug config
           run: cat admin/config.yml
         
         # Add your build steps here
         
         - name: Deploy
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./build  # adjust this to your build output directory

         - name: Debug before replacement
           run: cat admin/config.yml

          - name: Replace base_url placeholder
           run: |
             sed -i "s|NETLIFY_CMS_BASE_URL_PLACEHOLDER|${{ secrets.NETLIFY_CMS_BASE_URL }}|g" admin/config.yml

          - name: Debug after replacement
            run: cat admin/config.yml

          - name: Echo environment variable
            run: echo $NETLIFY_CMS_BASE_URL
