   name: Build and Deploy
   on:
     push:
       branches: [master]
   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         
         - name: Inject base_url
           run: |
             sed -i 's/repo: bsj2234\/bsj2234.github.io/&\n  base_url: ${{ secrets.NETLIFY_CMS_BASE_URL }}/' admin/config.yml
         
         - name: Debug config
           run: cat admin/config.yml
         
         # Add your build steps here
         
         - name: Deploy
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./build  # adjust this to your build output directory